name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-tests:
    name: Node.js service tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'order-service', 'payment-service', 'user-service' ]
        node-version: [ '20.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ matrix.service }}/package.json
      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm install
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: npm test --silent

  go-tests:
    name: Go service tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'inventory-service', 'catalog-service' ]
        go-version: [ '1.22.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set Go proxy
        run: go env -w GOPROXY=https://proxy.golang.org,direct
      - name: Download modules
        working-directory: ${{ matrix.service }}
        run: go mod download
      - name: Tidy modules
        working-directory: ${{ matrix.service }}
        run: go mod tidy
      - name: Run go tests
        working-directory: ${{ matrix.service }}
        run: go test ./...

  docker-build:
    name: Docker image build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'order-service', 'payment-service', 'user-service', 'inventory-service', 'catalog-service' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.service }} image
        run: |
          docker build -t bookstore/${{ matrix.service }}:ci ${{ matrix.service }}